# Generated by Django 4.2.24 on 2025-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('species', models.CharField(blank=True, max_length=100, verbose_name='Especie')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('watering_interval', models.PositiveIntegerField(default=7, verbose_name='Intervalo de riego (días)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio (MXN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
